version: "3.8"
services:
  db:
    image: postgres:15
    container_name: housing-db
    environment:
      POSTGRES_USER: housing
      POSTGRES_PASSWORD: housing
      POSTGRES_DB: housing
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  wildfly:
    image: jboss/wildfly:latest
    container_name: housing-wildfly
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=housing
      - POSTGRES_USER=housing
      - POSTGRES_PASSWORD=housing
    ports:
      - "8080:8080" # Для доступа к WildFly через браузер или Postman
      - "9990:9990" # Админ-панель WildFly
    volumes:
      - ./wildfly/deployments:/opt/jboss/wildfly/standalone/deployments:ro
      - ./wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:ro
    depends_on:
      - db